server:
  port: 9003
spring:
  application:
    name: BookService
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url=jdbc:mysql: jdbc:mysql://localhost:3306/casestudy
    username: root
    password: password

logging:
  file:
    name: C:\Users\e5659135\Downloads\CaseStudy\BookService\log\logdetails.log
    # Eureka server details
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/