server:
  port: 8088

logging:
  file:
    name: C:\Users\e5659135\Downloads\CaseStudy\api-gateway\log\logdetails.log

  # Eureka server details
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/ 
      
spring:
 application:
  name: api-gateway
 cloud:
  gateway:
   routes:
    - id: bookService
      uri: lb://BookService
      predicates:
       - Path=/books/**
    - id: subscriptionService
      uri: lb://SubscriptionService
      predicates:
       - Path=/subscriptions/**